# -- 主菜单 --

[[main]]
  name = "博客"
  pageRef = "blog"
  weight = 10

[[main]]
  identifier = "intro"
  name = "自我介绍"
  pre = "circle-info"
  weight = 20

[[main]]
  parent = "intro"
  name = "关于"
  pageRef = "about"
  weight = 10

[[main]]
  parent = "intro"
  name = "项目"
  pageRef = "projects"
  weight = 20

[[main]]
  parent = "intro"
  name = "Now"
  pageRef = "now"
  weight = 30

[[main]]
  name = "留言板"
  pageRef = "message"
  weight = 30

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 50

[[main]]
  identifier = "console"
  name = "个人控制台"
  pre = "globe"
  weight = 200

[[main]]
  parent = "console"
  name = "MCSManager"
  pre = "cloud"
  url = "https://mcsm.ydj001.xyz"
  weight = 10

[[main]]
  parent = "console"
  name = "EasyBot"
  pre = "bell"
  url = "https://easybot.ydj001.xyz"
  weight = 20

[[main]]
  parent = "console"
  name = "LLBot"
  pre = "comment"
  url = "https://bot.ydj001.xyz"
  weight = 30

[[main]]
  parent = "console"
  name = "FRP 面板"
  pre = "link"
  url = "https://frp.ydj001.xyz"
  weight = 40

[[main]]
  parent = "console"
  name = "Umami"
  pre = "eye"
  url = "https://umami.ydj001.xyz"
  weight = 50

# -- 页脚菜单 --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 30
